sudo: false
language: php
os:
  - linux
php:
  - 8.0
  allow_failures:
  - php: 8.0
before_script:
  - make install
script: composer run-script test
notifications:
  email: false
branches:
  only:
  - main
